name: Test GCP Workload Identity
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write # Kluczowe: pozwala GitHubowi wygenerować token OIDC

jobs:
  gcp-auth:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'github-actions-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Verify GCP Identity
      run: |
        gcloud auth list
        gcloud config get-value project
